[[permission]]
identifier = "allow-app-commands"
description = "Enables custom application commands"

[permission.commands]
allow = [
  "check_auth_state",
  "trigger_login",
  "clear_session",
  "fetch_from_ado",
  "save_file"
]
