name: Build

on:
  push:
    branches: [ main, feature/git-actions ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Use Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.x

    - name: Build Code
      run: |
        npm ci
        npm run build

    - name: Publish Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: dist
        path: dist/
        
    - name: Release 
      uses: bacongobbler/azure-blob-storage-upload@main
      with:
        source_dir: dist
        container_name: apps
        extra_args: '--destination-path ados-helper'
        connection_string: ${{ secrets.BLOB_CONNECTION_STRING }}
        overwrite: 'true'
