name: Build

on:
  push:
    branches: [ main, feature/git-actions ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Use Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.x

    - name: Build Code
      run: |
        npm ci
        npm run build

    - name: Publish Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: dist
        path: dist/

    - name: Release 
      uses: deka0106/upload-to-dropbox@v2
      with:
        dropbox_access_token: ${{ secrets.DROPBOX_ACCESS_TOKEN }}
        src: dist/index.js
        dest: /
        mode: overwrite
